#define TITLE "pong"
#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 800
#define TARGET_FPS 60
#define BALL_RADIUS 15
#define PLATFORM_WIDTH 10
#define PLATFORM_HEIGHT WINDOW_HEIGHT / 10
#define PLATFORM_SPEED 10
